//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomesticTransport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HeaderRow {
            get {
                return ((int)(this["HeaderRow"]));
            }
            set {
                this["HeaderRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SapUnloadPath {
            get {
                return ((string)(this["SapUnloadPath"]));
            }
            set {
                this["SapUnloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutlookFolders {
            get {
                return ((string)(this["OutlookFolders"]));
            }
            set {
                this["OutlookFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("whschaeffler@quehenberger.ru; Vadim Bogdanov <vadim.bogdanov@quehenberger.ru>; Mi" +
            "khail Borovik <Mikhail.Borovik@quehenberger.ru>")]
        public string SettingCSLetterTo {
            get {
                return ((string)(this["SettingCSLetterTo"]));
            }
            set {
                this["SettingCSLetterTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Sedova Galina  (ext.)  SWCSRG-LWA <sedovgli@schaeffler.com>; Koltsov Alexander  SWCSRG-LT <koltcaek@schaeffler.com>; Shurygina Alina  (ext.)  SWCSRG-LWA <shuryain@schaeffler.com>; Gumennikov Andrey  SWCSRG-ADC <gumenadr@schaeffler.com>; Morokhov Konstantin  SWCSRG-LWA <morokkns@schaeffler.com>; Sinyatkin Alexey  SWCSRG-LWA <SINYAAEX@schaeffler.com>; Konina Ekaterina  WI/SRG-CERO <konineat@schaeffler.com>; Chaplina Olga  WI/SRG-CERO <CHAPLOGA@schaeffler.com>; Sulak Olga  WI/SRG-CERO <sulakoga@schaeffler.com>; Kozlov Alexey  SWCSRG-ADC <alexey.kozlov@schaeffler.com>; Voitkevich Arkadii  SWCSRG-LT <voitkaka@schaeffler.com>; maxim.derbin@quehenberger.ru; Smorodov Vladimir  WI/SRG-CERO <smorovad@schaeffler.com>; Boldyreva Olga  WI/SRG-CERO <Tomskoga@schaeffler.com>; Zsilak Alekszandra  SWCSRG-ADC <zhilaaex@schaeffler.com>; Grinivezkaja Maria  SWCSRG-ADC <gerzomri@schaeffler.com>; Khovalyg Maadyr  WI/SRG-CERO <khovamad@schaeffler.com>; Grin Liliya  (ext.)  SWCSRG-LWA <grinlli@schaeffler.com>; Budnikova Iuliia  SWCSRG-ADC <budniili@schaeffler.com>")]
        public string SettingCSLetterCopy {
            get {
                return ((string)(this["SettingCSLetterCopy"]));
            }
            set {
                this["SettingCSLetterCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отгрузка на [date]")]
        public string SettingCSLetterSubject {
            get {
                return ((string)(this["SettingCSLetterSubject"]));
            }
            set {
                this["SettingCSLetterSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Коллеги, добрый день! В приложении отгрузка на [date], прошу принять к работе.")]
        public string SettingCSLetterMessage {
            get {
                return ((string)(this["SettingCSLetterMessage"]));
            }
            set {
                this["SettingCSLetterMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransportTableFileFullName {
            get {
                return ((string)(this["TransportTableFileFullName"]));
            }
            set {
                this["TransportTableFileFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipmentFileFullName {
            get {
                return ((string)(this["ShipmentFileFullName"]));
            }
            set {
                this["ShipmentFileFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HelpPath {
            get {
                return ((string)(this["HelpPath"]));
            }
            set {
                this["HelpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllOrders {
            get {
                return ((string)(this["AllOrders"]));
            }
            set {
                this["AllOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProviderLettersCopy {
            get {
                return ((string)(this["ProviderLettersCopy"]));
            }
            set {
                this["ProviderLettersCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявка грузоперевозки [provider] [date]")]
        public string ProviderSubjectOrder {
            get {
                return ((string)(this["ProviderSubjectOrder"]));
            }
            set {
                this["ProviderSubjectOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявка грузоперевозки [provider] [date]")]
        public string ProviderSubjectAdd {
            get {
                return ((string)(this["ProviderSubjectAdd"]));
            }
            set {
                this["ProviderSubjectAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отчет по доставкам [provider] за период [dateStart]-[dateEnd]")]
        public string ProviderSubjectReport {
            get {
                return ((string)(this["ProviderSubjectReport"]));
            }
            set {
                this["ProviderSubjectReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Коллеги, добрый день! В приложении отгрузка на [date], прошу принять к работе и " +
            "прислать до 17-00.")]
        public string ProviderMessageOrder {
            get {
                return ((string)(this["ProviderMessageOrder"]));
            }
            set {
                this["ProviderMessageOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Коллеги, добрый день! В приложении уточнения отгрузки на [date].")]
        public string ProviderMessageAdd {
            get {
                return ((string)(this["ProviderMessageAdd"]));
            }
            set {
                this["ProviderMessageAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Коллеги, добрый день! Отправляем отчет по доставкам за период [dateStart]-[dateE" +
            "nd]. Прошу заполнить столбцы, выделенные желтой заливкой.")]
        public string ProviderMessageReport {
            get {
                return ((string)(this["ProviderMessageReport"]));
            }
            set {
                this["ProviderMessageReport"] = value;
            }
        }
    }
}
